[symlinks]
"applications/code.desktop" = "/home/kaan/.local/share/applications/code.desktop"
"applications/com.logseq.Logseq.desktop" = "/home/kaan/.local/share/applications/com.logseq.Logseq.desktop"
"bottom/bottom.toml" = "/home/kaan/.config/bottom/bottom.toml"
"fish/completions/fisher.fish" = "/home/kaan/.config/fish/completions/fisher.fish"
"fish/completions/nvm.fish" = "/home/kaan/.config/fish/completions/nvm.fish"
"fish/conf.d/nvm.fish" = "/home/kaan/.config/fish/conf.d/nvm.fish"
"fish/config.fish" = "/home/kaan/.config/fish/config.fish"
"fish/fish_plugins" = "/home/kaan/.config/fish/fish_plugins"
"fish/fish_variables" = "/home/kaan/.config/fish/fish_variables"
"fish/functions/_nvm_index_update.fish" = "/home/kaan/.config/fish/functions/_nvm_index_update.fish"
"fish/functions/_nvm_list.fish" = "/home/kaan/.config/fish/functions/_nvm_list.fish"
"fish/functions/_nvm_version_activate.fish" = "/home/kaan/.config/fish/functions/_nvm_version_activate.fish"
"fish/functions/_nvm_version_deactivate.fish" = "/home/kaan/.config/fish/functions/_nvm_version_deactivate.fish"
"fish/functions/fisher.fish" = "/home/kaan/.config/fish/functions/fisher.fish"
"fish/functions/git-cleanup.fish" = "/home/kaan/.config/fish/functions/git-cleanup.fish"
"fish/functions/la.fish" = "/home/kaan/.config/fish/functions/la.fish"
"fish/functions/less.fish" = "/home/kaan/.config/fish/functions/less.fish"
"fish/functions/list-file-sizes.fish" = "/home/kaan/.config/fish/functions/list-file-sizes.fish"
"fish/functions/mkcd.fish" = "/home/kaan/.config/fish/functions/mkcd.fish"
"fish/functions/nvm.fish" = "/home/kaan/.config/fish/functions/nvm.fish"
"fish/functions/pacman-remove-orphans.fish" = "/home/kaan/.config/fish/functions/pacman-remove-orphans.fish"
"fish/functions/rust-musl.fish" = "/home/kaan/.config/fish/functions/rust-musl.fish"
"fish/functions/ssh.fish" = "/home/kaan/.config/fish/functions/ssh.fish"
"fish/functions/sway-prop.fish" = "/home/kaan/.config/fish/functions/sway-prop.fish"
"git/gitconfig" = "/home/kaan/.gitconfig"
"kitty/kitty.conf" = "/home/kaan/.config/kitty/kitty.conf"
"rofi/config/config.rasi" = "/home/kaan/.config/rofi/config.rasi"
"rofi/themes/powermenu.sh" = "/home/kaan/.local/share/rofi/themes/powermenu.sh"
"rofi/themes/rofi-advanced-7-2.rasi" = "/home/kaan/.local/share/rofi/themes/rofi-advanced-7-2.rasi"
"rofi/themes/rofi-advanced-powermenu-6-2.rasi" = "/home/kaan/.local/share/rofi/themes/rofi-advanced-powermenu-6-2.rasi"
"sway/config" = "/home/kaan/.config/sway/config"
"systemd/user/kdeconnectd.service" = "/home/kaan/.config/systemd/user/kdeconnectd.service"
"systemd/user/noisetorch.service" = "/home/kaan/.config/systemd/user/noisetorch.service"
"systemd/user/ssh-agent.service" = "/home/kaan/.config/systemd/user/ssh-agent.service"
"waybar/config" = "/home/kaan/.config/waybar/config"
"waybar/mediaplayer.py" = "/home/kaan/.config/waybar/mediaplayer.py"
"waybar/style.css" = "/home/kaan/.config/waybar/style.css"

[templates]
