[helpers]

[applications.files]
"applications/code.desktop" = "~/.local/share/applications/code.desktop"
"applications/com.logseq.Logseq.desktop" = "~/.local/share/applications/com.logseq.Logseq.desktop"

[bottom.files]
"bottom/bottom.toml" = "~/.config/bottom/bottom.toml"

[fish.files]
fish = "~/.config/fish"

[git.files]
"git/gitconfig" = "~/.gitconfig"

[kitty.files]
"kitty/kitty.conf" = "~/.config/kitty/kitty.conf"

[rofi]
depends = ["theme"]
[rofi.files]
"rofi/config/config.rasi" = "~/.config/rofi/config.rasi"
"rofi/themes/rofi-advanced-7-2.rasi" = "~/.local/share/rofi/themes/rofi-advanced-7-2.rasi"
"rofi/themes/rofi-advanced-powermenu-6-2.rasi" = "~/.local/share/rofi/themes/rofi-advanced-powermenu-6-2.rasi"
"rofi/themes/powermenu.sh" = "~/.local/share/rofi/themes/powermenu.sh"
"rofi/themes/launcher-bg.avif" = { target = "~/.local/share/rofi/themes/launcher-bg.avif", type = "symbolic" }
"rofi/themes/powermenu-bg.avif" = { target = "~/.local/share/rofi/themes/powermenu-bg.avif", type = "symbolic" }

[sway]
depends = ["theme"]
[sway.files]
"sway/config" = "~/.config/sway/config"
"sway/left.avif" = { target = "~/.config/sway/left.avif", type = "symbolic" }
"sway/middle.avif" = { target = "~/.config/sway/middle.avif", type = "symbolic" }
"sway/right.avif" = { target = "~/.config/sway/right.avif", type = "symbolic" }

[systemd.files]
"systemd/user/kdeconnectd.service" = "~/.config/systemd/user/kdeconnectd.service"
"systemd/user/noisetorch.service" = "~/.config/systemd/user/noisetorch.service"
"systemd/user/ssh-agent.service" = "~/.config/systemd/user/ssh-agent.service"

[waybar]
depends = ["theme"]
[waybar.files]
"waybar/config" = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"
"waybar/mediaplayer.py" = "~/.config/waybar/mediaplayer.py"


[theme.variables]
# These are specified in bg-fg pairs, background and text color. The _fg color
# is the color of text that would be readable on this color background.
#
# Dark doesn't necessarily mean darker tone, but also could be a duller tone. Or
# could be straight up lighter, just depends on the theme. It's just a variation
# of the color it's based on.
color_primary = "#66cc99"
color_primary_fg = "#000000"

color_primary_dark = "#94A879"
color_primary_dark_fg = "#000000"

color_primary_darker = "#5D7150"
color_primary_darker_fg = "#FFFFFF"

color_primary_darkest = "#807348"
color_primary_darkest_fg = "#FFFFFF"

color_secondary = "#D6882D"
color_secondary_fg = "#000000"

color_secondary_dark = "#9B551E"
color_secondary_dark_fg = "#FFFFFF"

color_secondary_darker = "#743307"
color_secondary_darker_fg = "#FFFFFF"

color_secondary_darkest = "#3F2D16"
color_secondary_darkest_fg = "#FFFFFF"
